#!/bin/sh
# osh_gen.sh: generate an osh unit source (lexer, parser) from the one layout list.
#   osh_gen.sh gen   LAYOUT TEMPLATE OUT_OSC OUT_H   write the generated files
#   osh_gen.sh check LAYOUT TEMPLATE OUT_OSC OUT_H   regenerate to a temp dir and require
#                                                    byte-identical checked-in files
# OSC has no constants or includes, so the template (osh_lex.osc.in) names every
# workspace offset as @NAME@ and sed substitutes the number. The C header carries the
# same names for the host. POSIX sh and sed only.
set -eu
export LC_ALL=C

mode=${1:?mode}
lst=${2:?layout}
tpl=${3:?template}
osc=${4:?out.osc}
hdr=${5:?out.h}

# NAME VALUE pairs, comments and blank lines dropped
pairs() {
	sed -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d' "$lst"
}

build() {
	out_osc=$1
	out_h=$2
	tmp=$(mktemp -d "${TMPDIR:-/tmp}/osh_gen.XXXXXX")
	trap 'rm -rf "$tmp"' EXIT
	pairs > "$tmp/pairs"
	# every line is exactly NAME VALUE; names unique; values decimal
	if grep -Env '^[A-Z][A-Z0-9_]* [0-9]+$' "$tmp/pairs" > "$tmp/bad"; [ -s "$tmp/bad" ]; then
		echo "osh_gen: bad layout line:" >&2
		cat "$tmp/bad" >&2
		exit 1
	fi
	dup=$(sed 's/ .*//' "$tmp/pairs" | sort | uniq -d)
	if [ -n "$dup" ]; then
		echo "osh_gen: duplicate layout name: $dup" >&2
		exit 1
	fi
	sed 's/^\([A-Z0-9_]*\) \([0-9]*\)$/s|@\1@|\2|g/' "$tmp/pairs" > "$tmp/sub.sed"
	{
		echo "// GENERATED by src/osh/osh_gen.sh from osh_layout.lst and $(basename "$tpl"). Do not edit; edit the .in or the list."
		sed -f "$tmp/sub.sed" "$tpl"
	} > "$out_osc"
	if grep -n '@[A-Z][A-Z0-9_]*@' "$out_osc" > "$tmp/left"; then
		echo "osh_gen: unresolved @NAME@ in template:" >&2
		cat "$tmp/left" >&2
		exit 1
	fi
	{
		echo "/* GENERATED by src/osh/osh_gen.sh from osh_layout.lst. Do not edit. */"
		echo "#ifndef OSH_LAYOUT_H"
		echo "#define OSH_LAYOUT_H"
		sed 's/^\([A-Z0-9_]*\) \([0-9]*\)$/#define OSH_\1 \2ULL/' "$tmp/pairs"
		echo "#endif /* OSH_LAYOUT_H */"
	} > "$out_h"
	rm -rf "$tmp"
	trap - EXIT
}

case $mode in
gen)
	build "$osc" "$hdr"
	;;
check)
	t=$(mktemp -d "${TMPDIR:-/tmp}/osh_gen_chk.XXXXXX")
	build "$t/o.osc" "$t/o.h"
	rc=0
	cmp -s "$t/o.osc" "$osc" || { echo "osh_gen: $osc is stale; run make osh-gen" >&2; rc=1; }
	cmp -s "$t/o.h" "$hdr" || { echo "osh_gen: $hdr is stale; run make osh-gen" >&2; rc=1; }
	rm -rf "$t"
	[ $rc -eq 0 ] && echo "osh_gen: check OK (generated files match the layout list)"
	exit $rc
	;;
*)
	echo "usage: osh_gen.sh gen|check LAYOUT TEMPLATE OUT_OSC OUT_H" >&2
	exit 2
	;;
esac
