#!/bin/bash
# Copy each evidence file of the CAND-2 window under its sha256 name and write CLAIM-INDEX.md.
# Status column = the DECLARED-ATTEMPTS.md pass rule applied to the file (written before the window).
set -eu
cd "$(dirname "$0")/.."
mkdir -p receipts
put() { local f=$1 h ext; h=$(sha256sum "$f" | cut -c1-64); ext=${f##*.}; cp --update=none "$f" "receipts/$h.$ext"; echo "$h"; }
row() { echo "| $1 | $2 | $3 | \`$4\` | \`$(put "$4")\` |"; }
R16=R16-ladder/raw/receipts/40742fdee4bbc4714b4742a70ff127c6033a478e426baf32fc787f0080378d53.json
R13=qual-runs-after-R13/20261005T181426Z-c62f47b5ac17/R13/rx_living_test_build_receipt.json
COMP=$(ls COMPOSITION-2-GPU/receipt-*.json)
R15LOG=$(ls R15-silicon/run-dir-progress.log 2>/dev/null || true)
{
echo "# CAND-2 window claim index (generated by 00-declared/collect_receipts.sh)"
echo
echo "Declared attempts sha256 \`$(sha256sum 00-declared/DECLARED-ATTEMPTS.md | cut -c1-64)\`. Every file below is also"
echo "copied to \`receipts/<sha256>.<ext>\`."
echo
echo "| Attempt | Claim | Status (declared rule) | Evidence file | sha256 |"
echo "|---|---|---|---|---|"
row A1 "R16 harness gates G1..G8" "R16 not PASS: G1-G5 PASS, G6 MISSING_IMPLEMENTATION, G7 NOT_RUN, G8 NOT_RUN (G6 and G7 accepted in advance)" "$R16"
row A1 "R16 harness console" "exit 3, R16_QUALIFY_RESULT=NOT_RUN" R16-ladder/stdout.log
row A1b "R11 living under load, living run exercised" "PASS: exit 0, checks 436 failures 0; positive marker line '[*] living run: moved from Cortex-A725 to Cortex-X925, AIEN notices and Omega re-realizes'; no 'living run not exercised'; 1-minute load 1.09 at start (rule: at most 2). The run takes under 1 s" R11-living/stdout.log
row A2 "R13 test build on silicon, candidate bound" "PASS: exit 0, R13_LIVING_SYSTEM_TEST_BUILD=PASS" "$R13"
row A3 "production hygiene on silicon" "PASS: exit 0, PROD_HYGIENE=PASS" prod-hygiene-silicon/stdout.log
row A4 "COMPOSITION-2 GPU tier" "PASS: exit 0, receipt PASS" "$COMP"
row A5 "CHIPWAIT 3/3 mechanical verdict" "PASS: 3 usable runs, 0 failed, 0 invalid" CHIPWAIT/campaign/final-verdict.json
for r in 1 2 3; do row A5 "M19R run $r: 18/18 M19 gates, 157/157 regression, soak 100000 cycles passed" "PASS" CHIPWAIT/campaign/run-00$r/run.json; done
row A6 "M18 full qualification" "PASS: exit 0, 18/18 M18 gates (36 evaluated)" M18/stdout.log
row A7 "R15 silicon performance acceptance" "NOT_RUN: harness defect. The r15 lane never builds the R15 programs and build/rx_r15_perf_silicon was absent (the chipwait lane's make clean is the likely reason; not shown). The energy preflight never ran: not an instrument refusal, not a performance result" "$R15LOG"
row A7b "R15 silicon, declared after A7 (DECLARED-ATTEMPT-A7b.md sha256 f56a97d6...e8db), rebuilt then run once" "BLOCKED_INSTRUMENT: INSTRUMENT_UNAVAILABLE, no hwmon named aien_spbm (the signed SPBM reader is not loaded), exit 4; as declared in advance. R15 not PASS, R16 G7 cannot pass" A7b-R15/R15-silicon/run-dir/progress.log
row A7b "R15 programs built for A7b" "built at c62f47b (make r15-perf-silicon, exit 0)" A7b-R15/R15-build/executables.sha256
echo
echo "Window: \`00-declared/window.txt\` (18:04:14Z to 18:23:25Z); A7b 18:26Z under its own 20-minute hold. Per-step command,"
echo "exit code, seconds and machine snapshots in each step directory."
echo
echo "## Conditions and limits (independent reconstruction, 2026-10-05)"
echo
echo "- Binding: the A1, A2 and A4 receipts name omega c62f47b and are candidate_bound with tree_dirty false; every"
echo "  snapshot heads.txt shows omega c62f47b and physics 6d7cf0d clean. The CHIPWAIT run.json files carry no commit:"
echo "  A5's binding rests on the command line and the snapshots. c62f47b is code-identical to 79a805d (ladder guard;"
echo "  git diff 79a805d c62f47b touches only the R16 map and .crumb files). The R13 receipt has aienos_commit unknown."
echo "- Foreign load present throughout and not stopped: GPU process pid 3456 (another account, atlas image python,"
echo "  18408 MiB, idle) and an idle ollama server (pid 3398861, up since 2026-10-04, 0.3 % CPU, about 36 MB, no model"
echo "  loaded). Xid count 0 before and after every step. 1-minute load 0.60 to 2.42."
echo "- A5 soak: 100000 cycles per run, the criterion exactly, in 41 to 43 s of chip time each: it meets the written"
echo "  rule, it is not hours of endurance."
echo "- A1: R16 is not PASS. G6 has 12 items, 11 PASS, operator_emergency_controls_passing MISSING_IMPLEMENTATION; G7"
echo "  NOT_RUN because no R15 PASS exists; G8 outside the script."
} > CLAIM-INDEX.md
