#include "pd0_codes.h"
#define C(x) case x: return #x;
const char *pd0v_name(int code)
{
    switch (code) {
    C(PD0V_OK) C(PD0V_BAD_MAGIC) C(PD0V_BAD_VERSION) C(PD0V_TRUNCATED) C(PD0V_HASH_MISMATCH) C(PD0V_CHAIN_BROKEN) C(PD0V_BAD_FIELD) C(PD0V_TOO_LARGE)
    C(PD0V_T1_TOO_FEW_RECORDS) C(PD0V_T1_TOO_FEW_EPISODES)
    C(PD0V_T2_NO_EVIDENCE) C(PD0V_T2_CORR_TOO_WEAK) C(PD0V_T2_P_TOO_HIGH) C(PD0V_T2_TOO_FEW_SHUFFLES) C(PD0V_T2_CORR_MISMATCH) C(PD0V_T2_TOO_FEW_RECORDS)
    C(PD0V_T3_NO_CANDIDATE) C(PD0V_T3_SIZE_EXCEEDED) C(PD0V_T3_FIT_ERROR_TOO_HIGH) C(PD0V_T3_RESIDUALS_NOT_WHITE) C(PD0V_T3_DEGREE_EXCEEDED) C(PD0V_T3_BAD_RELATION)
    C(PD0V_T4_NO_RIVAL) C(PD0V_T4_NO_FALSIFIER) C(PD0V_T4_EPS_ABOVE_BOUND) C(PD0V_T4_FALSIFIER_AFTER_TRIAL) C(PD0V_T4_UNKNOWN_CANDIDATE) C(PD0V_T4_UNKNOWN_RIVAL)
    C(PD0V_T5_TOO_FEW_PREREG) C(PD0V_T5_SCHEDULE_REUSED) C(PD0V_T5_MISSING_RIVAL_PREDICTION) C(PD0V_T5_PREREG_AFTER_TRIAL) C(PD0V_T5_OUT_OF_BOUNDS)
    C(PD0V_T6_TRIAL_MISSING) C(PD0V_T6_TRIAL_FAILED) C(PD0V_T6_TRIAL_NOT_PREREGISTERED)
    C(PD0V_T7_TOO_FEW_BATCHES) C(PD0V_T7_BATCH_TOO_SMALL) C(PD0V_T7_BATCH_FAILED) C(PD0V_T7_STREAM_REUSED) C(PD0V_T7_ORIGIN_IMBALANCE) C(PD0V_REP_INFLUENCED_FIT) C(PD0V_T7_EPISODE_ABOVE_3EPS)
    C(PD0V_T8_STATE_SKIPPED) C(PD0V_T8_CONFIDENCE_MISMATCH) C(PD0V_T8_EXCEPTIONS_MISMATCH) C(PD0V_T8_EXPERIMENT_MISSING) C(PD0V_T8_CHAIN_ROOT_MISMATCH) C(PD0V_T8_CLAIM_FORBIDDEN_WORD)
    C(PD0V_T8_CLAIM_TEXT_MISMATCH) C(PD0V_T8_DOMAIN_MISMATCH) C(PD0V_LAW_ID_MISMATCH) C(PD0V_LAW_DEMOTED) C(PD0V_T8_RELATION_MISMATCH) C(PD0V_T8_REFUTATION_COUNT_MISMATCH) C(PD0V_T8_STATE_MISMATCH)
    C(PD0V_SCORE_INBOX_NRMSE) C(PD0V_SCORE_EXTRAP_NRMSE) C(PD0V_SCORE_ONESTEP_NRMSE) C(PD0V_SCORE_SIZE) C(PD0V_SCORE_SUPPORT_MISSING) C(PD0V_SCORE_CONSTANT_OFF)
    C(PD0V_SCORE_DEGREE) C(PD0V_SCORE_L6_LATENT_MISSING) C(PD0V_SCORE_L6_REFERENCE_TOO_GOOD) C(PD0V_SCORE_BITS_MISMATCH) C(PD0V_RECEIPT_IO)
    default: return "PD0V_UNKNOWN";
    }
}
