#ifndef OMEGA_GPU_MATMUL_API_H
#define OMEGA_GPU_MATMUL_API_H
/*
 * omega_gpu_matmul_api: the native (no CUDA) matrix-multiply entry point for
 * the AIEN inference stack (FB-1 cut 1, 2026-10-03; cut 1b speed, 2026-10-04).
 *
 * Inputs are row-major bf16 (A: m x k, B: k x n), output is row-major f32
 * (C: m x n). Kernels are generated by our own codegen and cached in-process.
 *
 * Cut 1b:
 *  - the whole K dimension is accumulated on the chip (looped HMMA kernel,
 *    omega_blackwell_codegen_matmul_tensor_loop); no host K slicing;
 *  - the device and its channel are opened once per process and reused;
 *  - weights are uploaded once (omega_gpu_tensor_upload_*) and stay resident;
 *    omega_gpu_matmul_resident_* then moves only the activation rows and the
 *    result per call. The original omega_gpu_matmul_* calls keep working (they
 *    upload B, run, free) and keep running the host oracle per call as cut 1
 *    promised; the resident calls never run an oracle (speed), the caller or
 *    the test holds the reference.
 *  - every call poisons the output rows on the device before the launch and
 *    refuses a result that still holds poison (OUTPUT_UNCHANGED -> CHIP_FAIL).
 *  - an uncertain completion (marker wait timed out) latches the process:
 *    nothing is freed or closed (the GPU may still be running) and every later
 *    call returns CHIP_FAIL, as the engine does (omega_gpu_engine.h).
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum {
    OMEGA_GPU_MATMUL_OK = 0,
    OMEGA_GPU_MATMUL_BAD_ARGS = -1,     /* NULL pointer, zero dimension, shape mismatch, out of memory */
    OMEGA_GPU_MATMUL_TOO_LARGE = -2,    /* a dimension exceeds OMEGA_BW_MATMUL_MAX_* */
    OMEGA_GPU_MATMUL_CODEGEN_FAIL = -3, /* our codegen refused the shape */
    OMEGA_GPU_MATMUL_CHIP_FAIL = -4,    /* device open, alloc, submit, marker, release or output-written check failed */
    OMEGA_GPU_MATMUL_PARITY_FAIL = -5   /* chip result disagrees with the host oracle (non-resident calls only) */
};

/* Kernel tile rule (omega_blackwell_codegen_matmul_tensor_loop): M multiple of
 * 16, N multiple of 8, K multiple of 16. The API zero-pads: A rows/columns on
 * the way in per call, B at upload, and reads back only the real m x n block. */
#define OMEGA_GPU_MATMUL_TILE_M 16
#define OMEGA_GPU_MATMUL_TILE_N 8
#define OMEGA_GPU_MATMUL_TILE_K 16
/* Launch envelope. Cut 1 (2026-10-03 sweep, evidence GPU-MATMUL-API-2ea8e67,
 * investigation I42) saw grids of 128 CTAs and above lose output with the
 * single-tile kernel. The looped kernel does not need big grids: each CTA walks
 * column tiles x, x + grid_x, ... so any shape is one launch inside the budget
 * (rows are split across launches only when m / 16 alone exceeds it). The
 * budget is a tunable (omega_gpu_matmul_set_cta_budget) so the chip test can
 * measure larger grids; the default stays at the proven value until a sealed
 * receipt says otherwise. */
#define OMEGA_GPU_MATMUL_MAX_CTAS 64

typedef struct {
    uint32_t m, k, n;
    uint32_t padded_m, padded_n;/* shape handed to the kernel */
    uint32_t k_slices;          /* always 1 since cut 1b (whole K on the chip) */
    uint32_t chip_calls;        /* launches made (row blocks) */
    uint32_t rows_per_call;     /* row block height chosen for the CTA envelope */
    uint64_t elapsed_ns;        /* sum of chip launch-to-completion over the launches */
    float max_abs_err;          /* vs host oracle (non-resident calls only, else 0) */
    float max_rel_err;          /* vs host oracle, relative to the accumulation scale */
    size_t mismatch_count;      /* host oracle elements beyond tolerance (non-resident calls only) */
    bool parity_verified;       /* oracle ran and every element agreed (always false for resident calls) */
    uint32_t completion_marker; /* observed first marker word of the last launch */
    bool kernel_cache_hit;      /* every launch found its kernel already generated */
    char target_chip[64];
    uint32_t sm_architecture;
    /* cut 1b additions (appended; earlier fields keep their offsets) */
    uint32_t grid_x, grid_y;    /* grid of the last launch */
    uint32_t padded_k;
    bool resident;              /* B came from a resident tensor handle */
    bool oracle_ran;            /* the host oracle was computed for this call */
    uint64_t call_ns;           /* wall time of the whole API call (copy-in, launch, wait, copy-out) */
} OmegaGpuMatmulInfo;

/* Resident weight tensor: k x n bf16, zero-padded to the tile rule, kept in
 * GPU-uncached unified memory until freed. Opaque. */
typedef struct OmegaGpuTensor OmegaGpuTensor;

/* Upload a k x n row-major matrix once. f32 input is rounded to bf16 on the
 * host (round-to-nearest-even). Opens the device on first use. */
int omega_gpu_tensor_upload_bf16(uint32_t k, uint32_t n, const uint16_t *b, OmegaGpuTensor **out);
int omega_gpu_tensor_upload_f32(uint32_t k, uint32_t n, const float *b, OmegaGpuTensor **out);
void omega_gpu_tensor_free(OmegaGpuTensor *t);
void omega_gpu_tensor_shape(const OmegaGpuTensor *t, uint32_t *k, uint32_t *n);

/* C[m x n] = A[m x k] * B, B resident (k and n come from the handle). No host
 * oracle: info->parity_verified is false, mismatch_count 0. */
int omega_gpu_matmul_resident_bf16(uint32_t m, const uint16_t *a, const OmegaGpuTensor *b, float *c,
                                   OmegaGpuMatmulInfo *info);
int omega_gpu_matmul_resident_f32(uint32_t m, const float *a, const OmegaGpuTensor *b, float *c,
                                  OmegaGpuMatmulInfo *info);

/* C[m x n] = A[m x k] * B[k x n], bf16 inputs, f32 output. info may be NULL.
 * Uploads B for the call, runs, frees it, and checks the result against the
 * host oracle (double accumulation, tolerance 1e-5 of the accumulation scale). */
int omega_gpu_matmul_bf16(uint32_t m, uint32_t k, uint32_t n,
                          const uint16_t *a, const uint16_t *b, float *c,
                          OmegaGpuMatmulInfo *info);

/* Same, taking f32 inputs: they are rounded to bf16 on the host first
 * (round-to-nearest-even), so the result carries bf16 input precision. */
int omega_gpu_matmul_f32(uint32_t m, uint32_t k, uint32_t n,
                         const float *a, const float *b, float *c,
                         OmegaGpuMatmulInfo *info);

/* Name of a return code, for logs and receipts. */
const char *omega_gpu_matmul_rc_name(int rc);

/* Drop every cached kernel (host and device copies). */
void omega_gpu_matmul_cache_clear(void);

/* Close the device and free every API-owned buffer (not resident tensors the
 * caller still holds; free those first). Refused (no-op) after an uncertain
 * completion. The next call reopens. */
void omega_gpu_device_close(void);

/* 1 once an uncertain completion has latched this process. */
int omega_gpu_matmul_is_blocked(void);

/* CTA budget per launch (default OMEGA_GPU_MATMUL_MAX_CTAS; 0 restores it).
 * Clears the kernel cache (kernels bake in grid_x). Test and measurement knob. */
void omega_gpu_matmul_set_cta_budget(uint32_t ctas);
uint32_t omega_gpu_matmul_cta_budget(void);

/* Host oracle on the non-resident calls (default on). */
void omega_gpu_matmul_set_oracle(int on);

/* TEST ONLY. Non-zero generates deliberately wrong kernels (last K step
 * dropped) so the parity test can prove it catches a wrong kernel. Clears the
 * kernel cache. Production code must never call this. */
void omega_gpu_matmul_test_set_mutant(int on);

#ifdef __cplusplus
}
#endif
#endif
