#ifndef OMEGA_GPU_ATTENTION_API_H
#define OMEGA_GPU_ATTENTION_API_H
/*
 * omega_gpu_attention_api: native (no CUDA) decode attention for the AIEN
 * inference stack (FB-1 cut 5, 2026-10-04).
 *
 * Two kernel families, one query per (sequence, query head), generated by our
 * own codegen (src/omega_blackwell_codegen.c IR) and launched through the same
 * chip-proven sequence as cuts 1b and 4: every buffer GPU-uncached (nvos.h
 * NVOS32_ATTR2_GPU_CACHEABLE: system memory cached by the GPU is not coherent
 * with CPU mappings), shader caches invalidated before the launch (clcec0.h
 * NVCEC0_INVALIDATE_SHADER_CACHES, cut 1b finding), first marker,
 * L2_FLUSH_DIRTY, second marker (C3 tail), poison-filled output scanned for
 * unwritten words after readback.
 *
 * The math follows aien-sovereign-core crates/aien-inference-abi/src/backend.rs
 * (ReferenceCpuBackend / TensorBackend defaults), read 2026-10-04 at main 8b5caed:
 *   gqa_attention(out, q, k_cache, v_cache, seq_len, num_q_heads, num_kv_heads, head_dim)
 *     k_cache / v_cache are f32 [seq_len][num_kv_heads][head_dim]; query head h reads
 *     kv head h / (num_q_heads / num_kv_heads); score = (q . k) / sqrt(head_dim);
 *     softmax over all seq_len tokens (no mask: one query attends to the whole history);
 *     out[h] = sum_t softmax_t v_t.  seq_len == 0 writes zeros.
 *   paged_attention(out, q, pool, block_ids, context_len, layer_idx, ...)
 *     the KV pool is bf16 in aien-kv-cache's canonical layout (KvLayout strides in
 *     bytes: block, layer, kv plane (0 = K, 1 = V), token, head); token t lives in
 *     block_ids[t / block_size] at slot t % block_size; tokens whose block index is
 *     past the end of block_ids are dropped; context_len == 0 or no blocks writes zeros.
 *   paged_attention_batch: per sequence s, context_lens[s] <= 0 means 0, the block
 *     table row is block_tables[s*max_blocks .. (s+1)*max_blocks] (empty if that row
 *     runs past the array), negative entries are removed (the rest close up).
 *
 * Chip math: scores in f32 (FFMA over the head), online softmax per chunk of
 * head_dim tokens: running max (FMNMX), p = EX2((s - m) * log2 e) folded into the
 * score scale, rescale factor alpha = EX2(m_old - m_new), f32 sums, final MUFU.RCP.
 * bf16 K is read as 32-bit pairs (LDG.E) and widened by a 16-bit shift (bf16 is
 * the top half of an f32); bf16 V by LDG.E.U16 and the same shift. f32 K/V are
 * read directly. Tolerances are stated and justified in tests/gpu_attention_test.c.
 *
 * Launch envelope: at most OMEGA_GPU_ATTN_MAX_CTAS CTAs per launch (investigation
 * I42, same as cuts 1b and 4): grid = (num_q_heads, sequences per launch).
 * Shared memory: the QMD declares 1024 bytes (clcec0qmd.h SHARED_MEMORY_SIZE_SHIFTED7,
 * src/omega_blackwell_qmd.c word 36); the kernel uses exactly 4 x 256 bytes for
 * head_dim 64, so head_dim is fixed at 64 in this cut (TinyLlama and Llama-3.2-1B).
 *
 * Staging: the host copies q, the referenced KV blocks' layer slice, the (compacted,
 * renumbered) block tables and the context lengths into GPU-uncached staging buffers
 * for each launch and copies the result back. The kernel itself walks the block
 * table; a resident pool handle is a later cut.
 *
 * Cut 4b (2026-10-04): the device, channel and launch scratch are the process-wide
 * session shared with the matmul and elementwise APIs (omega_gpu_session.h): one
 * open per process instead of one per call (~40 ms), kernels resident after first
 * use, staging buffers reused at their high-water mark (the KV slice is written
 * straight into the device staging buffer). Calls serialise on one lock.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "omega_blackwell_matmul.h" /* OmegaBlackwellKernel */
#ifdef __cplusplus
extern "C" {
#endif

enum {
    OMEGA_GPU_ATTN_OK = 0,
    OMEGA_GPU_ATTN_BAD_ARGS = -1,     /* NULL pointer, zero dimension, head mapping or block id out of range */
    OMEGA_GPU_ATTN_TOO_LARGE = -2,    /* head_dim != 64, num_q_heads > 64, context past the envelope */
    OMEGA_GPU_ATTN_CODEGEN_FAIL = -3, /* our codegen refused or exceeded the register budget */
    OMEGA_GPU_ATTN_CHIP_FAIL = -4,    /* device open, alloc, submit, marker or release failed */
    OMEGA_GPU_ATTN_UNWRITTEN = -5     /* output words still equal to their poison after the run */
};

#define OMEGA_GPU_ATTN_HEAD_DIM 64u      /* threads per CTA = head_dim (one thread per dimension / per token of a chunk) */
#define OMEGA_GPU_ATTN_MAX_CTAS 64u
#define OMEGA_GPU_ATTN_MAX_Q_HEADS 64u
#define OMEGA_GPU_ATTN_MAX_GQA_CTX 4096u /* contiguous path: one block of 2^12 slots */

/* Mirror of aien-kv-cache KvLayoutDesc (crates/aien-kv-cache/src/lib.rs, main 8b5caed),
 * field for field, strides in bytes. */
typedef struct {
    uint64_t block_stride_bytes;
    uint64_t layer_stride_bytes;
    uint64_t kv_plane_stride_bytes;
    uint64_t token_stride_bytes;
    uint64_t head_stride_bytes;
    uint64_t pool_bytes;
    uint32_t num_blocks;
    uint32_t num_layers;
    uint32_t block_size; /* must be a power of two (the kernel shifts and masks) */
} OmegaGpuKvLayout;

typedef struct {
    uint32_t chip_calls;        /* launches made */
    uint64_t elapsed_ns;        /* sum of submit-to-second-marker over the launches */
    uint64_t call_ns;           /* wall time of the whole API call (staging, launches, copy-out) */
    uint32_t completion_marker; /* first marker word of the last launch */
    uint32_t unwritten_words;   /* poison words left in the outputs (0 on OK) */
    uint32_t gpr_count, insn_count;
    bool kernel_cache_hit;      /* the kernel was already generated */
    uint32_t ctas_last_launch, threads_per_cta;
    char target_chip[64];
    uint32_t sm_architecture;
} OmegaGpuAttnInfo;

/* Contiguous f32 KV (TensorBackend::gqa_attention). q and out: [num_q_heads][head_dim]. */
int omega_gpu_gqa_attention_f32(const float *q, const float *k_cache, const float *v_cache,
                                uint32_t seq_len, uint32_t num_q_heads, uint32_t num_kv_heads,
                                uint32_t head_dim, float *out, OmegaGpuAttnInfo *info);

/* Paged bf16 KV (TensorBackend::paged_attention). pool points at the pool base. */
int omega_gpu_paged_attention_bf16(const float *q, const void *pool, const OmegaGpuKvLayout *layout,
                                   const uint32_t *block_ids, uint32_t num_block_ids,
                                   uint32_t context_len, uint32_t layer_idx,
                                   uint32_t num_q_heads, uint32_t num_kv_heads, uint32_t head_dim,
                                   float *out, OmegaGpuAttnInfo *info);

/* Batched (TensorBackend::paged_attention_batch). block_tables: [num_seqs][max_blocks_per_seq] i32
 * (negative = none), context_lens: [num_seqs] i32. q and out: [num_seqs][num_q_heads][head_dim]. */
int omega_gpu_paged_attention_batch_bf16(const float *q, const void *pool, const OmegaGpuKvLayout *layout,
                                         const int32_t *block_tables, const int32_t *context_lens,
                                         uint32_t max_blocks_per_seq, uint32_t num_seqs, uint32_t layer_idx,
                                         uint32_t num_q_heads, uint32_t num_kv_heads, uint32_t head_dim,
                                         float *out, OmegaGpuAttnInfo *info);

const char *omega_gpu_attention_rc_name(int rc);
void omega_gpu_attention_cache_clear(void);

/* Stage name of the most recent CHIP_FAIL ("" if none), shared with the other GPU APIs
 * (omega_gpu_session_last_error); an open failure carries the driver text. */
const char *omega_gpu_attention_last_error(void);

/* Test hooks. Mutants are deliberately wrong kernels the parity test must catch;
 * never set in production. */
typedef enum {
    OMEGA_GPU_ATTN_MUTANT_NONE = 0,
    OMEGA_GPU_ATTN_MUTANT_NO_MAX,     /* softmax without the running-max subtraction (overflows for large scores) */
    OMEGA_GPU_ATTN_MUTANT_KV_HEAD,    /* reads kv head (h / ratio) ^ 1 */
    OMEGA_GPU_ATTN_MUTANT_SLOT,       /* K read from slot (t + 1) % block_size while V keeps slot t (K/V mismatch) */
    OMEGA_GPU_ATTN_MUTANT_NO_RESCALE, /* the accumulator is not rescaled when the max moves between chunks */
    /* Head-wiring mutants (attention hardening cut, 2026-10-04). Both swap the rows of
     * query heads h and h ^ 1, so they need num_q_heads even (>= 2); never run them on a
     * one-head shape (row h ^ 1 of the last sequence would be past the buffer). */
    OMEGA_GPU_ATTN_MUTANT_Q_ROW,      /* q loaded from query-head row h ^ 1 (kv head and output row stay h) */
    OMEGA_GPU_ATTN_MUTANT_OUT_ROW,    /* the correct result for head h stored in flattened output row h ^ 1 */
    OMEGA_GPU_ATTN_MUTANT_COUNT       /* one past the last mutant: every battery enumerates 1 .. COUNT-1 */
} OmegaGpuAttnMutant;
void omega_gpu_attention_test_set_mutant(OmegaGpuAttnMutant m);
/* "none", "NO_MAX", ... ; "?" past COUNT. The table is checked against COUNT at compile time. */
const char *omega_gpu_attention_mutant_name(OmegaGpuAttnMutant m);

/* Generate a kernel without launching (host tests, nvdisasm listings).
 * log2_block_size: shift for token -> block; log2_gqa: shift for query head -> kv head. */
int omega_gpu_attention_codegen(bool kv_f32, uint32_t log2_block_size, uint32_t log2_gqa,
                                OmegaBlackwellKernel *kernel);

/* One launch as the launcher sees it (test hook below). Pointers are host buffers;
 * params are the eight argument words after the four buffer addresses:
 * max_blocks, scale bits, block stride, token stride, kv plane stride, head stride,
 * num_q_heads, context-array byte offset. */
typedef struct {
    const void *q; size_t q_bytes;
    const void *pool; size_t pool_bytes;
    const void *tab; size_t tab_bytes;
    void *out; size_t out_bytes;
    uint32_t grid_x, grid_y;
    uint32_t params[8];
} OmegaGpuAttnLaunch;

/* Host simulator hook (tests): when set, every launch runs the allocated IR program
 * through `sim` instead of the chip. Lets the whole battery run on the host first
 * (review before chip time). The program is post register allocation. */
struct BlackwellIRProgramTag;
typedef int (*OmegaGpuAttnSim)(const void *prog /* const BlackwellIRProgram * */, const OmegaGpuAttnLaunch *L, OmegaGpuAttnInfo *info);
void omega_gpu_attention_test_set_simulator(OmegaGpuAttnSim sim);

#ifdef __cplusplus
}
#endif
#endif /* OMEGA_GPU_ATTENTION_API_H */
