#ifndef OMEGA_GPU_ELEMENTWISE_API_H
#define OMEGA_GPU_ELEMENTWISE_API_H
/*
 * omega_gpu_elementwise_api: native (no CUDA) elementwise and row-reduction
 * kernels for the AIEN inference stack (FB-1 cut 4, 2026-10-04).
 *
 * Three inference ops plus two probe ops, every kernel generated by our own
 * codegen (src/omega_blackwell_codegen.c IR) and launched through the same
 * chip-proven sequence as the tensor matmul path: all buffers GPU-uncached
 * (nvos.h NVOS32_ATTR2_GPU_CACHEABLE: system memory cached by the GPU is not
 * coherent with CPU mappings), first marker, L2_FLUSH_DIRTY, second marker
 * (C3 tail), poison-filled output scanned for unwritten words after readback.
 *
 * The math follows aien-sovereign-core crates/aien-inference-abi/src/tensor.rs
 * (ReferenceCpuBackend), read 2026-10-04 at main 5fdab70:
 *   rmsnorm:  scale = 1/sqrt(mean(x^2) + eps) (oracle sums in f64; the chip
 *             sums in f32 and uses MUFU.RSQ refined by one Newton step),
 *             out[i] = (x[i] * scale) * weight[i]  in that order.
 *   rope:     rotate_half pairs (i, i + head_dim/2) per head, cos/sin tables
 *             supplied by the host as f32 (the oracle casts f64 cos/sin to f32
 *             before the f32 math): out0 = q0*cos - q1*sin, out1 = q0*sin + q1*cos,
 *             emitted as FMUL, FMUL, FADD (no fused multiply-add), so the chip
 *             result is bit-identical to the f32 oracle.
 *   swiglu:   out = silu(gate) * up, silu(g) = g / (1 + exp(-g)); the chip uses
 *             MUFU.EX2(g * -log2(e)) and MUFU.RCP (approximate units), the
 *             oracle computes in f64. Tolerance is stated per op in the test.
 *
 * Cut 4b (2026-10-04): the device, channel and launch scratch are the process-wide
 * session shared with the matmul and attention APIs (omega_gpu_session.h): one open
 * per process instead of one per call (~40 ms), kernels resident after first use,
 * staging buffers reused at their high-water mark. Calls serialise on one lock.
 *
 * Launch envelope: at most OMEGA_GPU_EW_MAX_CTAS CTAs per launch (the matmul
 * sweep of 2026-10-03 lost whole tiles at 128 CTAs, investigation I42); the
 * API splits larger work on the host and makes several launches.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "omega_blackwell_matmul.h" /* OmegaBlackwellKernel */

#ifdef __cplusplus
extern "C" {
#endif

enum {
    OMEGA_GPU_EW_OK = 0,
    OMEGA_GPU_EW_BAD_ARGS = -1,     /* NULL pointer, zero dimension, or a shape rule below broken */
    OMEGA_GPU_EW_TOO_LARGE = -2,    /* dimension outside the codegen limits */
    OMEGA_GPU_EW_CODEGEN_FAIL = -3, /* our codegen refused or exceeded the register budget */
    OMEGA_GPU_EW_CHIP_FAIL = -4,    /* device open, submit, marker or release failed */
    OMEGA_GPU_EW_UNWRITTEN = -5     /* output words still equal to their poison after the run */
};

/* Kernel families. The two probes exist to prove the new instructions on the
 * chip with the smallest possible kernels (and are kept for regression). */
typedef enum {
    OMEGA_GPU_EW_EX2 = 1,     /* out[i] = 2^a[i]                       (probe for MUFU.EX2) */
    OMEGA_GPU_EW_XCHG,        /* out[i] = a[i ^ (T-1)] inside each CTA (probe for STS/BAR.SYNC/LDS) */
    OMEGA_GPU_EW_RMSNORM,
    OMEGA_GPU_EW_ROPE,
    OMEGA_GPU_EW_SWIGLU,
    OMEGA_GPU_EW_PRIME_SIEVE  /* prime race (2026-10-05): word-parallel odd-only sieve, codegen only
                               * here; launched by bench/prime_race/gb10_native.c (argument words in
                               * gen_prime_sieve's comment) */
} OmegaGpuEwOp;

/* Shape rules (checked, refused with BAD_ARGS / TOO_LARGE):
 *   rmsnorm: dim % OMEGA_GPU_EW_THREADS == 0, dim <= OMEGA_GPU_EW_MAX_DIM, rows >= 1
 *   rope:    head_dim even, 2 <= head_dim <= 2048 (head_dim/2 threads per CTA), heads >= 1
 *   swiglu:  n >= 1 (the kernel guards the tail with a predicated EXIT)
 *   ex2:     n >= 1;  xchg: n % OMEGA_GPU_EW_THREADS == 0 */
#define OMEGA_GPU_EW_THREADS 128u
#define OMEGA_GPU_EW_MAX_DIM 16384u
#define OMEGA_GPU_EW_MAX_CTAS 64u

typedef struct {
    uint32_t chip_calls;        /* launches made */
    uint64_t elapsed_ns;        /* sum of launch-to-second-marker over the launches */
    uint32_t completion_marker; /* observed first marker word of the last launch */
    uint32_t unwritten_words;   /* output words still equal to poison (0 on success) */
    bool kernel_cache_hit;      /* the shape's kernel was already generated in this process */
    uint32_t gpr_count;         /* registers the generated kernel uses */
    uint32_t insn_count;
    uint32_t threads_per_cta;
    uint32_t ctas_last_launch;
    char target_chip[64];
    uint32_t sm_architecture;
    uint64_t call_ns;           /* cut 4b: wall time of the whole API call (staging, launches, copy-out) */
} OmegaGpuEwInfo;

/* out[r*dim + i] = x[r*dim + i] * scale_r * weight[i]; scale_r = 1/sqrt(mean_i(x^2) + eps). */
int omega_gpu_rmsnorm_f32(uint32_t rows, uint32_t dim, const float *x, const float *weight,
                          float eps, float *out, OmegaGpuEwInfo *info);

/* v holds `heads` heads of head_dim values back to back; cos_half and sin_half
 * hold head_dim/2 values each (cos(pos*freq_i), sin(pos*freq_i)); out gets the
 * rotated heads (may alias v: the API copies through its own buffers). */
int omega_gpu_rope_f32(uint32_t heads, uint32_t head_dim, const float *v,
                       const float *cos_half, const float *sin_half, float *out,
                       OmegaGpuEwInfo *info);

/* out[i] = silu(gate[i]) * up[i] for i < n. */
int omega_gpu_swiglu_f32(uint32_t n, const float *gate, const float *up, float *out,
                         OmegaGpuEwInfo *info);

/* Probes. ex2: out[i] = 2^x[i]. xchg: out[i] = x[i ^ (OMEGA_GPU_EW_THREADS-1)] within each CTA. */
int omega_gpu_ex2_f32(uint32_t n, const float *x, float *out, OmegaGpuEwInfo *info);
int omega_gpu_shared_xchg_u32(uint32_t n, const uint32_t *x, uint32_t *out, OmegaGpuEwInfo *info);

/* Generate (without launching) the kernel for one op. Kernels read their shape
 * from the argument words, so one kernel per op serves every shape; dims and eps
 * are accepted for forward compatibility and ignored today (may be NULL / 0).
 * Lets tests disassemble the bytes offline (nvdisasm) and check the register
 * budget. Caller frees kernel->code. */
int omega_gpu_elementwise_codegen(OmegaGpuEwOp op, const uint32_t *dims, float eps,
                                  OmegaBlackwellKernel *kernel);

/* Same, with the mutant chosen by the caller (0 = production kernel) and, when prog is
 * not NULL, a copy of the allocated IR program (a BlackwellIRProgram, post register
 * allocation) for a host IR simulator. Does not touch the device or the kernel cache.
 * Caller frees kernel->code. */
int omega_gpu_elementwise_codegen_ir(OmegaGpuEwOp op, int mutant, void *prog,
                                     OmegaBlackwellKernel *kernel);

/* TEST ONLY. Selects a deliberately wrong kernel for one op (0 clears). Each
 * mutant changes the math by far more than the op's tolerance, so a parity
 * check that still passes against it proves nothing. Clears the kernel cache.
 *   EX2: computes 2^(x+1).  XCHG: reads its own shared word (no exchange).
 *   RMSNORM: the warp tree drops its last SHFL step (half the lanes go missing).
 *   ROPE: out0 = q0*cos + q1*sin.  SWIGLU: exp(+g) instead of exp(-g). */
void omega_gpu_elementwise_test_set_mutant(int op);

const char *omega_gpu_elementwise_rc_name(int rc);
void omega_gpu_elementwise_cache_clear(void);

/* Stage name of the most recent CHIP_FAIL ("" if none), shared with the other GPU APIs
 * (omega_gpu_session_last_error); an open failure carries the driver text. */
const char *omega_gpu_elementwise_last_error(void);

#ifdef __cplusplus
}
#endif
#endif
