#ifndef OMEGA_GPU_MATMUL_API_H
#define OMEGA_GPU_MATMUL_API_H
/*
 * omega_gpu_matmul_api: the first native (no CUDA) matrix-multiply entry point
 * for the AIEN inference stack (FB-1 cut 1, 2026-10-03).
 *
 * Wraps the chip-proven M16/M17 tensor matmul path (omega_blackwell_submit.c,
 * all buffers GPU-uncached, C3 release tail) behind a plain C call that a
 * Rust FFI crate can link. Inputs are row-major bf16 (A: m x k, B: k x n),
 * output is row-major f32 (C: m x n). Every call also runs the host oracle and
 * reports the error bound, so the first consumers get a parity receipt for free
 * (cost: one CPU matmul per call; a later cut makes the oracle optional).
 *
 * Kernels are generated by our own codegen per (m, k, n) and cached in-process.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum {
    OMEGA_GPU_MATMUL_OK = 0,
    OMEGA_GPU_MATMUL_BAD_ARGS = -1,     /* NULL pointer or zero dimension */
    OMEGA_GPU_MATMUL_TOO_LARGE = -2,    /* a dimension exceeds OMEGA_BW_MATMUL_MAX_* */
    OMEGA_GPU_MATMUL_CODEGEN_FAIL = -3, /* our codegen refused the shape */
    OMEGA_GPU_MATMUL_CHIP_FAIL = -4,    /* device open, submit, marker or release failed */
    OMEGA_GPU_MATMUL_PARITY_FAIL = -5   /* chip result disagrees with the host oracle */
};

/* Kernel shape rule today (omega_blackwell_codegen_matmul_tensor): M multiple of
 * 16, N multiple of 8, K exactly 16. The API hides it: A and B are zero-padded
 * on the host to (Mp x 16) and (16 x Np) slices, one chip call per 16-wide K
 * slice, partial products summed on the host in f32. Correct for any shape up
 * to the limits; the per-slice device open/submit cost is the known price until
 * the in-kernel K loop lands (FB-1 cut 1b). */
#define OMEGA_GPU_MATMUL_TILE_M 16
#define OMEGA_GPU_MATMUL_TILE_N 8
#define OMEGA_GPU_MATMUL_TILE_K 16
/* Chip-proven launch envelope (2026-10-03 sweep, evidence GPU-MATMUL-API-2ea8e67):
 * grids of <= 100 CTAs return correct tiles, 128 and above lose whole tiles
 * (investigation I42). The API never launches more than this many CTAs per
 * call and splits rows on the host above it. */
#define OMEGA_GPU_MATMUL_MAX_CTAS 64

typedef struct {
    uint32_t m, k, n;
    uint32_t padded_m, padded_n;/* shape handed to the kernel */
    uint32_t k_slices;          /* 16-wide K slices: ceil(k / 16) */
    uint32_t chip_calls;        /* launches made (slices x row blocks) */
    uint32_t rows_per_call;     /* row block height chosen for the CTA envelope */
    uint64_t elapsed_ns;        /* sum of chip launch-to-completion over the slices */
    float max_abs_err;          /* vs host bf16 oracle */
    float max_rel_err;
    size_t mismatch_count;
    bool parity_verified;       /* every slice agreed with the host oracle */
    uint32_t completion_marker; /* observed first marker word of the last slice */
    bool kernel_cache_hit;      /* the padded shape's kernel was already generated */
    char target_chip[64];
    uint32_t sm_architecture;
} OmegaGpuMatmulInfo;

/* C[m x n] = A[m x k] * B[k x n], bf16 inputs, f32 output. info may be NULL. */
int omega_gpu_matmul_bf16(uint32_t m, uint32_t k, uint32_t n,
                          const uint16_t *a, const uint16_t *b, float *c,
                          OmegaGpuMatmulInfo *info);

/* Same, taking f32 inputs: they are rounded to bf16 on the host first
 * (round-to-nearest-even), so the result carries bf16 input precision. */
int omega_gpu_matmul_f32(uint32_t m, uint32_t k, uint32_t n,
                         const float *a, const float *b, float *c,
                         OmegaGpuMatmulInfo *info);

/* Name of a return code, for logs and receipts. */
const char *omega_gpu_matmul_rc_name(int rc);

/* Drop every cached kernel (tests; otherwise never needed). */
void omega_gpu_matmul_cache_clear(void);

#ifdef __cplusplus
}
#endif
#endif
